ALTER TABLE student
ADD CONSTRAINT age_constraint CHECK (age > 16);

ALTER TABLE student
ADD CONSTRAINT name_not_null UNIQUE(name);

ALTER TABLE student
ALTER COLUMN name SET NOT NULL;

ALTER TABLE faculty
ADD PRIMARY KEY(name, color);

ALTER TABLE student
ALTER COLUMN age SET DEFAULT 20;
